### ISSUE TITLE
Improve formatting to better mimic academic papers using CSS

### ISSUE THREAD

**Issue by piranna** [Hammie217/LatexJekyll#3]
- [ ] justify text. Not too common nor pretty on web, but standard of printed texts https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_text-justify
- [ ] two columns layout https://www.w3schools.com/css/tryit.asp?filename=trycss3_column-count

**Comment by turian** [comment]
Justified text would be a nice option

**Comment by Hammie217** [comment]
Better late than never but both added in [this commit](https://github.com/Hammie217/LatexJekyll/commit/a05c27060c66fc7b8ad0bb04bbc069953b0b4f45)

Thanks for the great suggestions!

**Comment by piranna** [comment]
You are welcome :-) Now that I'm thinking, I believe there's some CSS to mark end of pages too, so they could also emulated the same way of the two columns :-)
